### ISSUE TITLE
En el frontend

### ISSUE THREAD

**Issue by einar-lanfranco** [arielleguizamon/dsa-tp-final#1]
~/dsa-tp-final/frontend# npm install 
npm ERR! install Couldn't read dependencies
npm ERR! Error: Invalid name: "@coreui/coreui-free-react-admin-template"
npm ERR!     at ensureValidName (/usr/lib/nodejs/normalize-package-data/lib/fixer.js:284:15)
npm ERR!     at Object.module.exports.fixNameField (/usr/lib/nodejs/normalize-package-data/lib/fixer.js:199:5)
npm ERR!     at /usr/lib/nodejs/normalize-package-data/lib/normalize.js:29:38
npm ERR!     at Array.forEach (native)
npm ERR!     at normalize (/usr/lib/nodejs/normalize-package-data/lib/normalize.js:28:15)
npm ERR!     at final (/usr/lib/nodejs/read-package-json/read-json.js:342:33)
npm ERR!     at then (/usr/lib/nodejs/read-package-json/read-json.js:126:33)
npm ERR!     at /usr/lib/nodejs/read-package-json/read-json.js:266:40
npm ERR!     at evalmachine.<anonymous>:272:14
npm ERR!     at /usr/lib/nodejs/graceful-fs/graceful-fs.js:102:5
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /root/dsa-tp-final/frontend
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/dsa-tp-final/frontend/npm-debug.log
npm ERR! not ok code 0

**Comment by einar-lanfranco** [comment]
root@lamp2017:~/dsa-tp-final/frontend# nodejs -v
v0.10.29
root@lamp2017:~/dsa-tp-final/frontend# npm -v
1.4.21

**Comment by arielleguizamon** [comment]
Versión requerida de node > 8

**Comment by einar-lanfranco** [comment]
juro q segui las instrucciones de https://github.com/nodesource/distributions/blob/master/README.md#deb

**Comment by arielleguizamon** [comment]
capaz te quedó la versión de nodejs que viene el sistema, intentá eliminarla o pisarla con el nuevo binario
