### ISSUE TITLE
En la api

### ISSUE THREAD

**Issue by einar-lanfranco** [arielleguizamon/dsa-tp-final#2]
npm install
npm WARN package.json base-admin@1.0.0 No README data
npm WARN engine bcrypt@3.0.2: wanted: {"node":">= 6.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})

> bcrypt@3.0.2 install /root/dsa-tp-final/api/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

/usr/bin/env: node: No existe el fichero o el directorio
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! bcrypt@3.0.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the bcrypt@3.0.2 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /root/dsa-tp-final/api
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/dsa-tp-final/api/npm-debug.log
npm ERR! not ok code 0

**Comment by einar-lanfranco** [comment]
root@lamp2017:~/dsa-tp-final/frontend# nodejs -v
v0.10.29
root@lamp2017:~/dsa-tp-final/frontend# npm -v
1.4.21

**Comment by arielleguizamon** [comment]
Versión requerida de nodejs  > 8
